/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Tinder App API Documentation
 * Tinder App API documentation for the application

## Demo User

A demo user is available for testing the API:

**Credentials:**
- Email: `demo@demo.app`
- Password: `password`

**Profile Information:**
- Name: Demo User
- Age: 25
- Location: New York, NY
- Gender: M
- Pictures: 3 pictures included

You can use these credentials to login and test all API endpoints.
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DislikePerson200,
  DislikePersonBody,
  GetAuthenticatedUser200,
  GetAuthenticatedUser401,
  GetInteractedPeopleIds200,
  GetLikedPeople200,
  GetRecommendedPeople200,
  GetRecommendedPeopleParams,
  GetUser200,
  GetUser401,
  LikePerson200,
  LikePersonBody,
  LoginUser200,
  LoginUser401,
  LoginUser422,
  LoginUserBody,
  LogoutUser200,
  LogoutUser401,
  UndoLastAction200,
  UndoLastAction404
} from './models';

import { customInstance } from '../mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Authenticate a user and return an access token
 * @summary Login user
 */
export const loginUser = (
    loginUserBody: LoginUserBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LoginUser200>(
      {url: `/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginUserBody, signal
    },
      options);
    }
  


export const getLoginUserMutationOptions = <TError = LoginUser401 | LoginUser422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginUserBody}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: LoginUserBody}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = LoginUserBody
    export type LoginUserMutationError = LoginUser401 | LoginUser422

    /**
 * @summary Login user
 */
export const useLoginUser = <TError = LoginUser401 | LoginUser422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: LoginUserBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: LoginUserBody},
        TContext
      > => {

      const mutationOptions = getLoginUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns the currently authenticated user information
 * @summary Get authenticated user
 */
export const getAuthenticatedUser = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetAuthenticatedUser200>(
      {url: `/me`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAuthenticatedUserQueryKey = () => {
    return [
    `/me`
    ] as const;
    }

    
export const getGetAuthenticatedUserQueryOptions = <TData = Awaited<ReturnType<typeof getAuthenticatedUser>>, TError = GetAuthenticatedUser401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthenticatedUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthenticatedUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthenticatedUser>>> = ({ signal }) => getAuthenticatedUser(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthenticatedUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAuthenticatedUserQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthenticatedUser>>>
export type GetAuthenticatedUserQueryError = GetAuthenticatedUser401


export function useGetAuthenticatedUser<TData = Awaited<ReturnType<typeof getAuthenticatedUser>>, TError = GetAuthenticatedUser401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthenticatedUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthenticatedUser>>,
          TError,
          Awaited<ReturnType<typeof getAuthenticatedUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthenticatedUser<TData = Awaited<ReturnType<typeof getAuthenticatedUser>>, TError = GetAuthenticatedUser401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthenticatedUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthenticatedUser>>,
          TError,
          Awaited<ReturnType<typeof getAuthenticatedUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAuthenticatedUser<TData = Awaited<ReturnType<typeof getAuthenticatedUser>>, TError = GetAuthenticatedUser401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthenticatedUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated user
 */

export function useGetAuthenticatedUser<TData = Awaited<ReturnType<typeof getAuthenticatedUser>>, TError = GetAuthenticatedUser401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthenticatedUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAuthenticatedUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Revoke the current access token and logout the user
 * @summary Logout user
 */
export const logoutUser = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LogoutUser200>(
      {url: `/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getLogoutUserMutationOptions = <TError = LogoutUser401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext> => {

const mutationKey = ['logoutUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutUser>>, void> = () => {
          

          return  logoutUser(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
    
    export type LogoutUserMutationError = LogoutUser401

    /**
 * @summary Logout user
 */
export const useLogoutUser = <TError = LogoutUser401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns a paginated list of recommended people for the authenticated user
 * @summary Get recommended people
 */
export const getRecommendedPeople = (
    params?: GetRecommendedPeopleParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetRecommendedPeople200>(
      {url: `/people`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetRecommendedPeopleQueryKey = (params?: GetRecommendedPeopleParams,) => {
    return [
    `/people`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetRecommendedPeopleQueryOptions = <TData = Awaited<ReturnType<typeof getRecommendedPeople>>, TError = void>(params?: GetRecommendedPeopleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendedPeople>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecommendedPeopleQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecommendedPeople>>> = ({ signal }) => getRecommendedPeople(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecommendedPeople>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRecommendedPeopleQueryResult = NonNullable<Awaited<ReturnType<typeof getRecommendedPeople>>>
export type GetRecommendedPeopleQueryError = void


export function useGetRecommendedPeople<TData = Awaited<ReturnType<typeof getRecommendedPeople>>, TError = void>(
 params: undefined |  GetRecommendedPeopleParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendedPeople>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendedPeople>>,
          TError,
          Awaited<ReturnType<typeof getRecommendedPeople>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecommendedPeople<TData = Awaited<ReturnType<typeof getRecommendedPeople>>, TError = void>(
 params?: GetRecommendedPeopleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendedPeople>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendedPeople>>,
          TError,
          Awaited<ReturnType<typeof getRecommendedPeople>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRecommendedPeople<TData = Awaited<ReturnType<typeof getRecommendedPeople>>, TError = void>(
 params?: GetRecommendedPeopleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendedPeople>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get recommended people
 */

export function useGetRecommendedPeople<TData = Awaited<ReturnType<typeof getRecommendedPeople>>, TError = void>(
 params?: GetRecommendedPeopleParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecommendedPeople>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRecommendedPeopleQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Like a person
 * @summary Like a person
 */
export const likePerson = (
    likePersonBody: LikePersonBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LikePerson200>(
      {url: `/people/like`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: likePersonBody, signal
    },
      options);
    }
  


export const getLikePersonMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof likePerson>>, TError,{data: LikePersonBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof likePerson>>, TError,{data: LikePersonBody}, TContext> => {

const mutationKey = ['likePerson'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof likePerson>>, {data: LikePersonBody}> = (props) => {
          const {data} = props ?? {};

          return  likePerson(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LikePersonMutationResult = NonNullable<Awaited<ReturnType<typeof likePerson>>>
    export type LikePersonMutationBody = LikePersonBody
    export type LikePersonMutationError = void | void

    /**
 * @summary Like a person
 */
export const useLikePerson = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof likePerson>>, TError,{data: LikePersonBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof likePerson>>,
        TError,
        {data: LikePersonBody},
        TContext
      > => {

      const mutationOptions = getLikePersonMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Dislike a person
 * @summary Dislike a person
 */
export const dislikePerson = (
    dislikePersonBody: DislikePersonBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DislikePerson200>(
      {url: `/people/dislike`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dislikePersonBody, signal
    },
      options);
    }
  


export const getDislikePersonMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dislikePerson>>, TError,{data: DislikePersonBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof dislikePerson>>, TError,{data: DislikePersonBody}, TContext> => {

const mutationKey = ['dislikePerson'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dislikePerson>>, {data: DislikePersonBody}> = (props) => {
          const {data} = props ?? {};

          return  dislikePerson(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DislikePersonMutationResult = NonNullable<Awaited<ReturnType<typeof dislikePerson>>>
    export type DislikePersonMutationBody = DislikePersonBody
    export type DislikePersonMutationError = void | void

    /**
 * @summary Dislike a person
 */
export const useDislikePerson = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dislikePerson>>, TError,{data: DislikePersonBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof dislikePerson>>,
        TError,
        {data: DislikePersonBody},
        TContext
      > => {

      const mutationOptions = getDislikePersonMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns a list of all people the authenticated user has liked
 * @summary Get liked people list
 */
export const getLikedPeople = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetLikedPeople200>(
      {url: `/people/liked`, method: 'GET', signal
    },
      options);
    }
  



export const getGetLikedPeopleQueryKey = () => {
    return [
    `/people/liked`
    ] as const;
    }

    
export const getGetLikedPeopleQueryOptions = <TData = Awaited<ReturnType<typeof getLikedPeople>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLikedPeople>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLikedPeopleQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLikedPeople>>> = ({ signal }) => getLikedPeople(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLikedPeople>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLikedPeopleQueryResult = NonNullable<Awaited<ReturnType<typeof getLikedPeople>>>
export type GetLikedPeopleQueryError = void


export function useGetLikedPeople<TData = Awaited<ReturnType<typeof getLikedPeople>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLikedPeople>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLikedPeople>>,
          TError,
          Awaited<ReturnType<typeof getLikedPeople>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLikedPeople<TData = Awaited<ReturnType<typeof getLikedPeople>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLikedPeople>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLikedPeople>>,
          TError,
          Awaited<ReturnType<typeof getLikedPeople>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLikedPeople<TData = Awaited<ReturnType<typeof getLikedPeople>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLikedPeople>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get liked people list
 */

export function useGetLikedPeople<TData = Awaited<ReturnType<typeof getLikedPeople>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLikedPeople>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLikedPeopleQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Undo the last like or dislike action performed by the authenticated user
 * @summary Undo last action
 */
export const undoLastAction = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<UndoLastAction200>(
      {url: `/people/undo`, method: 'POST', signal
    },
      options);
    }
  


export const getUndoLastActionMutationOptions = <TError = void | UndoLastAction404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undoLastAction>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof undoLastAction>>, TError,void, TContext> => {

const mutationKey = ['undoLastAction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof undoLastAction>>, void> = () => {
          

          return  undoLastAction(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UndoLastActionMutationResult = NonNullable<Awaited<ReturnType<typeof undoLastAction>>>
    
    export type UndoLastActionMutationError = void | UndoLastAction404

    /**
 * @summary Undo last action
 */
export const useUndoLastAction = <TError = void | UndoLastAction404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undoLastAction>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof undoLastAction>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getUndoLastActionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Returns an array of all people IDs that the authenticated user has interacted with (liked or disliked)
 * @summary Get all interacted people IDs
 */
export const getInteractedPeopleIds = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetInteractedPeopleIds200>(
      {url: `/people/interactions`, method: 'GET', signal
    },
      options);
    }
  



export const getGetInteractedPeopleIdsQueryKey = () => {
    return [
    `/people/interactions`
    ] as const;
    }

    
export const getGetInteractedPeopleIdsQueryOptions = <TData = Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInteractedPeopleIdsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInteractedPeopleIds>>> = ({ signal }) => getInteractedPeopleIds(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInteractedPeopleIdsQueryResult = NonNullable<Awaited<ReturnType<typeof getInteractedPeopleIds>>>
export type GetInteractedPeopleIdsQueryError = void


export function useGetInteractedPeopleIds<TData = Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInteractedPeopleIds>>,
          TError,
          Awaited<ReturnType<typeof getInteractedPeopleIds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInteractedPeopleIds<TData = Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInteractedPeopleIds>>,
          TError,
          Awaited<ReturnType<typeof getInteractedPeopleIds>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInteractedPeopleIds<TData = Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all interacted people IDs
 */

export function useGetInteractedPeopleIds<TData = Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInteractedPeopleIds>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInteractedPeopleIdsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Returns the currently authenticated user information
 * @summary Get the authenticated user
 */
export const getUser = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetUser200>(
      {url: `/user`, method: 'GET', signal
    },
      options);
    }
  



export const getGetUserQueryKey = () => {
    return [
    `/user`
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser401>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = GetUser401


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser401>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get the authenticated user
 */

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = GetUser401>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




