/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Tinder App API Documentation
 * Tinder App API documentation for the application

## Demo User

A demo user is available for testing the API:

**Credentials:**
- Email: `demo@demo.app`
- Password: `password`

**Profile Information:**
- Name: Demo User
- Age: 25
- Location: New York, NY
- Gender: M
- Pictures: 3 pictures included

You can use these credentials to login and test all API endpoints.
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */
import type { GetLikedPeople200DataItemPicturesItem } from './getLikedPeople200DataItemPicturesItem';
import type { GetLikedPeople200DataItemGender } from './getLikedPeople200DataItemGender';

export type GetLikedPeople200DataItem = {
  id?: number;
  user_id?: number;
  name?: string;
  age?: number;
  pictures?: GetLikedPeople200DataItemPicturesItem[];
  location?: string;
  gender?: GetLikedPeople200DataItemGender;
  created_at?: string;
  updated_at?: string;
};
