/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Tinder App API Documentation
 * Tinder App API documentation for the application

## Demo User

A demo user is available for testing the API:

**Credentials:**
- Email: `demo@demo.app`
- Password: `password`

**Profile Information:**
- Name: Demo User
- Age: 25
- Location: New York, NY
- Gender: M
- Pictures: 3 pictures included

You can use these credentials to login and test all API endpoints.
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export type GetRecommendedPeople200DataItemGender = typeof GetRecommendedPeople200DataItemGender[keyof typeof GetRecommendedPeople200DataItemGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRecommendedPeople200DataItemGender = {
  M: 'M',
  F: 'F',
} as const;
