/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Tinder App API Documentation
 * Tinder App API documentation for the application

## Demo User

A demo user is available for testing the API:

**Credentials:**
- Email: `demo@demo.app`
- Password: `password`

**Profile Information:**
- Name: Demo User
- Age: 25
- Location: New York, NY
- Gender: M
- Pictures: 3 pictures included

You can use these credentials to login and test all API endpoints.
 * OpenAPI spec version: 1.0.0
 * tslint:disable
 * @ts-nocheck
 */

export * from './dislikePerson200';
export * from './dislikePersonBody';
export * from './getAuthenticatedUser200';
export * from './getAuthenticatedUser401';
export * from './getInteractedPeopleIds200';
export * from './getLikedPeople200';
export * from './getLikedPeople200DataItem';
export * from './getLikedPeople200DataItemGender';
export * from './getLikedPeople200DataItemPicturesItem';
export * from './getRecommendedPeople200';
export * from './getRecommendedPeople200DataItem';
export * from './getRecommendedPeople200DataItemGender';
export * from './getRecommendedPeople200DataItemPicturesItem';
export * from './getRecommendedPeople200LinksItem';
export * from './getRecommendedPeopleParams';
export * from './getUser200';
export * from './getUser401';
export * from './likePerson200';
export * from './likePersonBody';
export * from './loginUser200';
export * from './loginUser200User';
export * from './loginUser401';
export * from './loginUser422';
export * from './loginUser422Errors';
export * from './loginUserBody';
export * from './logoutUser200';
export * from './logoutUser401';
export * from './undoLastAction200';
export * from './undoLastAction200Data';
export * from './undoLastAction200DataAction';
export * from './undoLastAction404';